export const PROMOTION_PATHS: Record<string, string[]> = {
  'Adept': ['FireWizard', 'DarkSorcerer'],
  'Alchemist': ['ElementalAlchemist'],
  'AncientLich': ['LorfOfDecay'],
  'Angel': ['Archangel'],
  'Apprentice': ['LightDisciple', 'Adept'],
  'Archer': ['Huntress'],
  'Assassin': ['SpireInitiate', 'RedStalker'],
  'Bard': ['Lorekeeper'],
  'Blight': ['Wraith'],
  'Cleric': ['WhiteMage'],
  'Cutthroat': ['Assassin'],
  'DarkKnight': ['DeathKnight'],
  'DarkSorcerer': ['Necromancer'],
  'DeathKnight': ['Scourge'],
  'Demilich': ['Lich'],
  'Demon': ['InfernalLord'],
  'DivineDuelist': ['DivineChampion'],
  'DrakeRider': ['GoldenRider'],
  'ElementalAlchemist': ['EsotericAlchemist'],
  'EsotericAlchemist': ['EldritchAlchemist'],
  'FireWizard': ['RedMage'],
  'Footman': ['Warrior'],
  'Fury': ['Hailstorm'],
  'GoldenRider': ['WyrmRider'],
  'Guard': ['IronWarden', 'RoyalGuard'],
  'Hailstorm': ['Tempest'],
  'HeavenlyCantor': ['Eidolon'],
  'HellishSculptor': ['SpiritEngraver'],
  'HolyKnight': ['Paladin'],
  'HorseRider': ['WolfRider'],
  'Huntress': ['HorseRider', 'Marksman'],
  'Hurricane': ['CelestialRain'],
  'InfernalLord': ['InfernalPrince'],
  'InfernalPrince': ['Balrog'],
  'Inquisitor': ['Justiciar'],
  'IronDefender': ['Juggernaut'],
  'IronWarden': ['IronDefender'],
  'Juggernaut': ['Titan'],
  'Justiciar': ['AngelOfWar'],
  'KingsHand': ['DivineDuelist'],
  'Knight': ['DarkKnight', 'HolyKnight'],
  'Lich': ['AncientLich'],
  'LightDisciple': ['Cleric'],
  'Lorekeeper': ['HeavenlyCantor'],
  'LorfOfDecay': ['BlackIdol'],
  'Marksman': ['Sureshot', 'PoisonBow'],
  'MeatCarver': ['WoundsWeaver'],
  'MeltingElder': ['Inferno'],
  'Minstrel': ['Bard'],
  'Necromancer': ['Demilich', 'Unchained'],
  'NightBlade': ['NightSpecter'],
  'NightSpecter': ['NightTerror'],
  'NightTerror': ['NightVeil'],
  'NightVeil': ['NightLament'],
  'Overlord': ['BlackRegent'],
  'Paladin': ['Templar'],
  'PlagueSpreader': ['Blight'],
  'PoisonBow': ['ToxicStalker'],
  'RadiantElder': ['Angel'],
  'RedArchmage': ['RedElder'],
  'RedElder': ['ScorchingElder'],
  'RedMage': ['RedArchmage'],
  'RedStalker': ['MeatCarver'],
  'Rogue': ['Thief'],
  'RoyalCaptain': ['KingsHand'],
  'RoyalGuard': ['RoyalSwordsman'],
  'RoyalSwordsman': ['RoyalCaptain'],
  'ScorchingElder': ['MeltingElder'],
  'Scourge': ['Tyrant'],
  'ShadowCrawler': ['ShadowDancer'],
  'ShadowDancer': ['NightBlade'],
  'SilverTongue': ['Minstrel'],
  'SpireAcolyte': ['SpireLeader'],
  'SpireInitiate': ['SpireAcolyte'],
  'SpireLeader': ['SpireSage'],
  'SpireSage': ['Whisper'],
  'SpitfangRider': ['DrakeRider'],
  'Sureshot': ['Fury'],
  'Tempest': ['Hurricane'],
  'Templar': ['Inquisitor'],
  'Thief': ['ShadowCrawler', 'Cutthroat', 'Trickster'],
  'Titan': ['UndyingBastion'],
  'ToxicStalker': ['PlagueSpreader', 'Alchemist'],
  'Trickster': ['SilverTongue'],
  'Tyrant': ['Overlord'],
  'Unchained': ['Demon'],
  'UndyingBastion': ['EternalFortress'],
  'Warrior': ['Guard', 'Knight'],
  'WhiteArchmage': ['WhiteElder'],
  'WhiteElder': ['RadiantElder'],
  'WhiteMage': ['WhiteArchmage'],
  'WolfRider': ['WorgRider'],
  'WorgRider': ['SpitfangRider'],
  'WoundsWeaver': ['HellishSculptor'],
  'Wraith': ['CorrosiveWraith'],
}
